### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ideprecated** [ChristianPerez34/lifeline_crypto_tbot#62]
Hey there, I'm interested in what you've created, although I'm a bit lost of how to run it and what it does. I downloaded the project and opened it in VSCode and I think gathered up all the dependencies. Maybe if you could give me a nudge in the right direction or tell me what do that would help. If you're looking for contributors I know of a few people that might be willing to get involved.

Thanks!

**Comment by ChristianPerez34** [comment]
Hi, sorry for the late reply!

First of all we are using [Poetry](https://python-poetry.org/docs/) as our dependency manager. All installs are recommended to be done using this tool. 

The basis of the bot is to quickly gather information on crypto currencies (price, charts, alerts, buy, sell, etc) and display them in a telegram group for members to take advantage of. 

In order to run the bot you will need a couple of things,

1. Create a bot in Telegram by talking with [TheBotFather](https://core.telegram.org/bots#6-botfather)
2. Create a .env file and input below keys (Not all of them are required. Only depends on the commands you intend to use)
    - ENV
    -   TELEGRAM_BOT_API_KEY
    -   COIN_MARKET_CAP_API_KEY
    -   KUCOIN_API_KEY
    -   KUCOIN_API_SECRET
    -   KUCOIN_API_PASSPHRASE
    -   TELEGRAM_CHAT_ID
    -   BSCSCAN_API_KEY
    -   DB_NAME
    -   DB_HOST
    -   DB_USER
    -   DB_PASSWORD
    -   FERNET_KEY
    -   ETHERSCAN_API_KEY
3. Have some fun
